[package]
name = "vst3-bindgen"
version = "0.1.0"
edition = "2021"

[dependencies]
com-scrape-types = { path = "com-scrape-types" }

[build-dependencies]
com-scrape = { path = "com-scrape" }

[[example]]
name = "gain"
crate-type = ["cdylib"]

[workspace]
members = [
    "com-scrape",
    "com-scrape-types",
]
